// Checkout UI Sample for deep dive to how the extension gets loaded in Preact JSX and hooks.
// Read https://shopify.dev/docs/api/checkout-ui-extensions
// Read https://shopify.dev/docs/api/checkout-ui-extensions/extension-points-api
// Read https://shopify.dev/docs/api/checkout-ui-extensions/latest/apis/attributes
// Read https://shopify.dev/docs/api/checkout-ui-extensions/latest/apis/discounts
// Read https://shopify.dev/docs/api/checkout-ui-extensions/latest/apis/buyer-journey
// Read https://shopify.dev/docs/api/checkout-ui-extensions/components

import '@shopify/ui-extensions/preact';
import {render} from 'preact';
import {useEffect, useState} from 'preact/hooks';

// My own common functions shared by multiple files.
import {commonFuncExternal} from './common';

// The following extension registration needs to be the same as `./shopify.extension.toml`.
// Read https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration
// Added for the dynamic target (generated by CLI by default).
// API versions 2025-10 and later use one module entry point per target.
export default async () => {
  render(<Extension />, document.body);
};

export function Extension() {
  const api = shopify;
  // console.log(`Extension() api target: ${api.extension.target}`);

  const instructions = api.instructions.value;

  // Read https://shopify.dev/docs/apps/build/app-extensions/configure-app-extensions
  const {read_metafields, read_attributes, read_discounts} = api.settings.value;
  console.log(`Extension() / settings read_metafields: ${read_metafields} read_attributes: ${read_attributes} read_discounts: ${read_discounts}`);

  let appMetafield1 = '';
  let appMetafield2 = '';
  if (read_metafields == null || read_metafields === true) {
    // The following appMetafields can retrieve all metafields with target type specification.
    // Read https://shopify.dev/docs/api/checkout-ui-extensions/latest/apis/metafields
    // NOTE THAT Preact hooks cannot be called in callbacks like Button.onClick(), which means you have to read the
    // data through signals like metafields, attributes, discount codes, and shipping address in the loading, not in
    // callbacks like button clicks. Check https://preactjs.com/guide/v10/hooks/
    appMetafield1 = api.appMetafields.value
      .filter((entry) => entry.target.type === 'shop' && entry.metafield.namespace === 'barebone_app' && entry.metafield.key === 'url')
      .map((entry) => entry.metafield.value)
      .join(' ');
    appMetafield2 = api.appMetafields.value
      .filter((entry) => entry.target.type === 'product' && entry.metafield.namespace === 'barebone_app_upsell' && entry.metafield.key === 'product_id')
      .map((entry) => entry.metafield.value)
      .join(' ');
    console.log(`Extension() / appMetafield1: ${appMetafield1} appMetafield2: ${appMetafield2}`);

    // This is another approach for getting app metafields data without useEffect.
    // If you don't use Preact hooks, you can do this with subscribe() through api directly. Check `./Checkout.js`.
    /* api.appMetafields.value.map((entry) => {
      console.log(`Extension() / appMetafields map() / data: ${JSON.stringify(entry)}`);
    }); */

    // Checkout-related metafields are available through the matching signal on the target API.
    // Read https://shopify.dev/docs/api/checkout-ui-extensions/latest/apis/metafields
  }

  // Read https://preactjs.com/guide/v10/hooks/#useeffect
  useEffect(() => {
    // This is the timing of some of metafields changed (including empty values).
    // If you want to do something like fetch external URL with the value, write here.
    console.log(`Extension() / useEffect() / appMetafield1: ${appMetafield1} appMetafield2: ${appMetafield2}`);

    // If the metafields are not retrieved yet, return and expect to get them in the next loading.
    if (appMetafield1 === '' || appMetafield2 === '') return;

    // DO SOMETHING
  }, [appMetafield1, appMetafield2]);

  // Check if the discount update eligibility.
  if (!instructions.discounts.canUpdateDiscountCodes) {
    return <s-banner tone="warning">Loyalty discounts are unavailable</s-banner>;
  }

  let attrValue = '';
  let discountCode = '';
  if (read_attributes == null || read_attributes === true) {
    // Get the current cart attribute value of the discount code.
    // (This is supposed to the same attribute in `./my-theme-app-ext/blocks/app-block.liquid`)
    attrValue = api.attributes.value
      .filter((attribute) => attribute.key === 'barebone_cart_attribute_code')
      .map((attribute) => attribute.value)
      .join('');
    console.log(`Extension() / attrValue: ${attrValue}`);
  }
  if (read_discounts == null || read_discounts === true) {
    // Get the current discount code to be in the cart attribute above.
    discountCode = api.discountCodes.value.map((code) => code.code).join('');
    console.log(`Extension() / discountCode: ${JSON.stringify(discountCode)}`);
  }

  // Control the checkout block based on the result of applying discount code.
  const [block, setBlock] = useState(false);
  const [blockMessage, setBlockMessage] = useState('');
  const [blockReason, setBlockReason] = useState('');
  useEffect(() => {
    const interceptPromise = api.buyerJourney.intercept(({canBlockProgress}) => (
      canBlockProgress && block
        ? {
          behavior: 'block',
          reason: blockReason,
          errors: [{message: blockMessage}],
        }
        : {behavior: 'allow'}
    ));
    return () => {
      interceptPromise.then((stopIntercepting) => stopIntercepting());
    };
  }, [block, blockMessage, blockReason]);

  // Read https://preactjs.com/guide/v10/hooks/#useeffect
  useEffect(() => {
    // This is the timing of the current attribute value OR discount code changed (including empty values).
    console.log(`Extension() / useEffect() / attrValue: ${attrValue} discountCode: ${discountCode}`);

    // Buyer operation cases between cart and checkout
    if (attrValue === '' && discountCode === '') {
      // No discount code set in cart or checkout (Case 0).
      // Do nothing.
      console.log(`Extension() / useEffect() / Case 0`);
    } else if (attrValue !== '' && discountCode === '') {
      // The buyer set the code in cart and it is being applied to checkout initially (Case 1), or
      // the buyer remove the code in checkout (Case 2).
      api.storage.read('applied').then((cache) => {
        // For detecting Case 1 or 2, use local storage cache in the browser.
        if (cache == null) {
          // If the cache is empty, Case 1 = initial loading.
          api.applyDiscountCodeChange({
            type: 'addDiscountCode',
            code: attrValue,
          }).then((res) => {
            console.log(`Extension() / useEffect() / Case 1 applyDiscountCodeChange type: addDiscountCode code: ${attrValue} response: ${JSON.stringify(res)}`);
            if (res.type === 'error') {
              // If the code fails to be applied, block the checkout.
              setBlock(true);
              setBlockMessage('Set your discount code again.');
              setBlockReason('Failed to apply the given discount code.');
            } else {
              // If the code gets applied successfully, unblock the checkout, and write the cache flag.
              setBlock(false);
              setBlockMessage('');
              setBlockReason('');
              api.storage.write('applied', 'true');
            }
          }).catch((error) => {
            console.log(`Extension() / useEffect() / Case 1 applyDiscountCodeChange type: addDiscountCode code: ${attrValue} exception: ${JSON.stringify(error)}`);
          });
        } else {
          // If the cache exists, Case 2 = buyer's manual input after the loading.
          api.applyAttributeChange({
            type: 'updateAttribute',
            key: 'barebone_cart_attribute_code',
            value: '',
          }).then((res) => {
            console.log(`Extension() / useEffect() / Case 2 applyAttributeChange value: ${discountCode} response: ${JSON.stringify(res)}`);
            // Clear the cache for the next initial loading after back and forth to cart.
            api.storage.delete('applied');
          }).catch((error) => {
            console.log(`Extension() / useEffect() / Case 2 applyAttributeChange value: ${discountCode} exception: ${JSON.stringify(error)}`);
          });
        }
      });
    } else if (attrValue !== '' && discountCode !== '') {
      // The buyer set the code in cart and it has been applied to checkout (Case 3), or
      // the buyer changed the code in checkout (Case 4).
      if (attrValue === discountCode) {
        // Case 3, do nothing.
        console.log(`Extension() / useEffect() / Case 3`);
      } else {
        // Case 4, overwrite the attribute with the current code (if they want to reset, they need to clear the code in Case 2)
        api.applyAttributeChange({
          type: 'updateAttribute',
          key: 'barebone_cart_attribute_code',
          value: discountCode,
        }).then((res) => {
          console.log(`Extension() / useEffect() / Case 4 applyAttributeChange value: ${discountCode} response: ${JSON.stringify(res)}`);
        }).catch((error) => {
          console.log(`Extension() / useEffect() / Case 4 applyAttributeChange value: ${discountCode} exception: ${JSON.stringify(error)}`);
        });
      }
    } else if (attrValue === '' && discountCode !== '') {
      // The buyer didn't set the code in cart but did in checkout (Case 5).
      api.applyAttributeChange({
        type: 'updateAttribute',
        key: 'barebone_cart_attribute_code',
        value: discountCode,
      }).then((res) => {
        console.log(`Extension() / useEffect() / Case 5 applyAttributeChange value: ${discountCode} response: ${JSON.stringify(res)}`);
      }).catch((error) => {
        console.log(`Extension() / useEffect() / Case 5 applyAttributeChange value: ${discountCode} exception: ${JSON.stringify(error)}`);
      });
    } else {
      // No cases.
    }
  }, [attrValue, discountCode]);

  // Check the current discount allocations.
  /* api.discountAllocations.value.map((allocation) => {
    console.log(`Extension() / discountAllocations / data: ${JSON.stringify(allocation)}`);
  }); */

  // Checking the common function in the same file.
  commonFuncInFile(`Extension() / test text 1`);
  // Checking the common function in the external file.
  commonFuncExternal(`Extension() / test text 1`);

  return (
    <s-stack direction="block" gap="base" border="base base dotted" padding="small">
      <s-banner heading="api.extension.target (Preact)">
        <s-text type="strong">
          {api.i18n.translate('welcome', {target: `Dynamic: ${api.extension.target}`})}
        </s-text>
      </s-banner>
      <s-banner><s-text type="strong">App Metafield 1 Value: </s-text>{appMetafield1}</s-banner>
      <s-banner><s-text type="strong">App Metafield 2 Value: </s-text>{appMetafield2}</s-banner>
      <s-banner><s-text type="strong">Your current attribute value: </s-text>{attrValue}</s-banner>
      <s-banner><s-text type="strong">Your current discount code: </s-text>{discountCode}</s-banner>
      <s-banner tone="warning">
        <s-checkbox
          label="Check this to unblock the checkout"
          checked={!block}
          error={blockReason}
          onChange={(event) => {
            const checked = Reflect.get(event.currentTarget || {}, 'checked');
            setBlock(!checked);
            if (!checked) {
              setBlockMessage('Check the warning box below.');
              setBlockReason('The checkbox is not checked.');
            } else {
              setBlockMessage('');
              setBlockReason('');
            }
          }}
        />
      </s-banner>
    </s-stack>
  );
}

export function ExtensionStatic() {
  const api = shopify;

  console.log(`ExtensionStatic() / Do nothing, no UI`);
  // Checking the common function in the same file.
  commonFuncInFile(`ExtensionStatic() / test text 2`);
  // Checking the common function in the external file.
  commonFuncExternal(`ExtensionStatic() / test text 2`);

  // If you toggle the following codes uncommented, this function = ExtensionStatic() gets executed multiple times.
  // const {read_metafields, read_attributes, read_discounts} = api.settings.value;
  // console.log(`ExtensionStatic() / settings read_metafields: ${read_metafields} read_attributes: ${read_attributes} read_discounts: ${read_discounts}`);

  // `value` of the signal always contains the current settings.
  const {read_metafields, read_attributes, read_discounts} = api.settings.value;
  console.log(`ExtensionStatic() / api.settings read_metafields: ${read_metafields} read_attributes: ${read_attributes} read_discounts: ${read_discounts}`);

  return (
    <s-banner heading="api.extension.target (Preact)" tone="critical">
      <s-text type="strong">
        {api.i18n.translate('welcome', {target: `Static: ${api.extension.target}`})}
      </s-text>
    </s-banner>
  );
}

// Common function in the same file.
const commonFuncInFile = (text) => {
  console.log(`commonFuncInFile outputs with text: ${text}`);
};
