// Checkout UI Sample for deep dive to how the extension gets loaded in Vanilla JS without Preact JSX or hooks.
// Read https://shopify.dev/docs/api/checkout-ui-extensions
// Read https://shopify.dev/docs/api/checkout-ui-extensions/extension-points-api
// Read https://shopify.dev/docs/api/checkout-ui-extensions/latest/apis/attributes
// Read https://shopify.dev/docs/api/checkout-ui-extensions/latest/apis/discounts
// Read https://shopify.dev/docs/api/checkout-ui-extensions/components

// My own common functions shared by multiple files.
import {commonFuncExternal} from './common';

// The following extension registration needs to be the same as `./shopify.extension.toml`.
// Read https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration
// Added for the dynamic target (generated by CLI by default).
// API versions 2025-10 and later use one module entry point per target.
export default async () => {
  Extension(document.body, /** @type {any} */ (shopify));
};

/**
 * @param {HTMLElement} root
 * @param {import('@shopify/ui-extensions/purchase.checkout.block.render').Api} api
 */
export function Extension(root, api) {
  console.log(`Extension() api target: ${api.extension.target}`);

  const {read_metafields, read_attributes, read_discounts} = api.settings.value;
  console.log(`Extension() / api.settings read_metafields: ${read_metafields} read_attributes: ${read_attributes} read_discounts: ${read_discounts}`);

  let appMetafield1 = '';
  let appMetafield2 = '';
  let attrValue = '';
  let discountCode = '';

  // Function to reactivate (render again) the components that is called when the following metafields / attributes / discounts codes
  // subscribe() callbacks get new values.
  // Read https://shopify.dev/docs/api/checkout-ui-extensions/latest/apis
  const renderUI = () => {
    const blockStack = createComponent('s-stack', {
      direction: 'block',
      gap: 'base',
      border: 'base base dotted',
      padding: 'small',
    }, [
      createBanner('api.extension.target (Vanilla JS)', api.i18n.translate('welcome', {
        target: `Dynamic: ${api.extension.target}`,
      })),
      createBanner('', `App Metafield 1 Value: ${appMetafield1}`),
      createBanner('', `App Metafield 2 Value: ${appMetafield2}`),
      createBanner('', `Your current attribute value: ${attrValue}`),
      createBanner('', `Your current discount code: ${discountCode}`),
    ]);
    root.replaceChildren(blockStack);
  };

  if (read_metafields == null || read_metafields === true) {
    // Read https://shopify.dev/docs/api/checkout-ui-extensions/latest/apis/metafields
    // The API fields are signals. Read `value` for current data and use subscribe() to react to later changes.
    // NOTE THAT subscribe's callback happens async, so keep values outside the callback when they are needed by event handlers.
    api.appMetafields.subscribe((entry) => {
      console.log(`Extension() / api.appMetafields.subscribe entry: ${JSON.stringify(entry)}`);
      appMetafield1 = '';
      appMetafield2 = '';
      entry.forEach((item) => {
        if (item.target.type === 'shop' && item.metafield.namespace === 'barebone_app' && item.metafield.key === 'url') appMetafield1 = item.metafield.value;
        if (item.target.type === 'product' && item.metafield.namespace === 'barebone_app_upsell' && item.metafield.key === 'product_id') appMetafield2 = item.metafield.value;
      });
      console.log(`Extension() / api.appMetafields.subscribe appMetafield1: ${appMetafield1} appMetafield2 ${appMetafield2}`);
      // Instead of useEffect and useState in Preact hooks, reactivate the components directly.
      renderUI();
    });
  }

  if (read_attributes == null || read_attributes === true) {
    // Read https://shopify.dev/docs/api/checkout-ui-extensions/latest/apis/attributes
    api.attributes.subscribe((entry) => {
      // Unlike Preact signals in `Checkout.jsx`, Vanilla JS doesn't render Extension() again when values change,
      // so call renderUI() from subscribe callbacks.
      console.log(`Extension() / api.attributes.subscribe entry: ${JSON.stringify(entry)}`);
      attrValue = entry
        .filter((attribute) => attribute.key === 'barebone_cart_attribute_code')
        .map((attribute) => attribute.value)
        .join('');
      console.log(`Extension() / api.attributes.subscribe attrValue: ${attrValue}`);
      // Instead of useEffect and useState in Preact hooks, reactivate the components directly.
      renderUI();
      if (attrValue !== '') {
        api.storage.read('value').then((cache) => {
          // Update the code only when the value has changed using local storage cache.
          if (cache === attrValue) return;
          api.applyDiscountCodeChange({
            type: 'addDiscountCode',
            code: attrValue,
          }).then((res) => {
            console.log(`Extension() / api.attributes.subscribe / applyDiscountCodeChange type: addDiscountCode code: ${attrValue} response: ${JSON.stringify(res)}`);
            // Write the cache.
            api.storage.write('value', attrValue);
          }).catch((error) => {
            console.log(`Extension() / api.attributes.subscribe / applyDiscountCodeChange type: addDiscountCode code: ${attrValue} exception: ${JSON.stringify(error)}`);
          });
        });
      }
    });
  }

  if (read_discounts == null || read_discounts === true) {
    // Read https://shopify.dev/docs/api/checkout-ui-extensions/latest/apis/discounts
    api.discountCodes.subscribe((entry) => {
      console.log(`Extension() / api.discountCodes.subscribe entry: ${JSON.stringify(entry)}`);
      discountCode = entry.map((discount) => discount.code).join('');
      console.log(`Extension() / api.discountCodes.subscribe discountCode: ${discountCode}`);
      // Instead of useEffect and useState in Preact hooks, reactivate the components directly.
      renderUI();
      if (discountCode !== '') {
        api.storage.read('code').then((cache) => {
          // Update the attribute only when the value has changed using local storage cache as a flag.
          if (cache === discountCode) return;
          api.applyAttributeChange({
            type: 'updateAttribute',
            key: 'barebone_cart_attribute_code',
            value: discountCode,
          }).then((res) => {
            console.log(`Extension() / api.discountCodes.subscribe / applyAttributeChange value: ${discountCode} response: ${JSON.stringify(res)}`);
            // Write the cache.
            api.storage.write('code', discountCode);
          }).catch((error) => {
            console.log(`Extension() / api.discountCodes.subscribe / applyAttributeChange value: ${discountCode} exception: ${JSON.stringify(error)}`);
          });
        });
      }
    });
  }

  // Checking the common function in the same file.
  commonFuncInFile(`Extension() / test text 1`);
  // Checking the common function in the external file.
  commonFuncExternal(`Extension() / test text 1`);

  renderUI();
  return root;
}

/**
 * @param {HTMLElement} root
 * @param {import('@shopify/ui-extensions/purchase.checkout.actions.render-before').Api} api
 */
export function ExtensionStatic(root, api) {
  console.log(`ExtensionStatic() / Do nothing, no UI`);
  // Checking the common function in the same file.
  commonFuncInFile(`ExtensionStatic() / test text 2`);
  // Checking the common function in the external file.
  commonFuncExternal(`ExtensionStatic() / test text 2`);

  // `value` contains the current settings without manually subscribing.
  const {read_metafields, read_attributes, read_discounts} = api.settings.value;
  console.log(`ExtensionStatic() / api.settings read_metafields: ${read_metafields} read_attributes: ${read_attributes} read_discounts: ${read_discounts}`);

  root.replaceChildren(createBanner('api.extension.target (Vanilla JS)', api.i18n.translate('welcome', {
    target: `Static: ${api.extension.target}`,
  }), 'critical'));
  return root;
}

/**
 * @param {string} heading
 * @param {any} content
 * @param {'auto' | 'critical'} tone
 */
function createBanner(heading, content, tone = 'auto') {
  return createComponent('s-banner', {heading, tone}, [createComponent('s-text', {type: 'strong'}, [content])]);
}

/**
 * @param {string} tagName
 * @param {Record<string, any>} properties
 * @param {any[]} children
 */
function createComponent(tagName, properties = {}, children = []) {
  const element = document.createElement(tagName);
  Object.assign(element, properties);
  children.forEach((child) => element.append(child));
  return element;
}

// Common function in the same file.
/** @param {string} text */
const commonFuncInFile = (text) => {
  console.log(`commonFuncInFile outputs with text: ${text}`);
};
