name = "my-function-payment-ext"
type = "payment_customization"
api_version = "unstable"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/my-function-payment-ext.wasm"
watch = [ "src/**/*.rs" ]

[ui.paths]
create = "/functionpayment"
details = "/functionpayment"
