api_version = "2026-07"

[[extensions]]
name = "my-function-payment-ext"
handle = "my-function-payment-ext"
uid = "db1fde78-bf9a-42ea-afb6-89f0edbb4797"
type = "function"

  [[extensions.targeting]]
  target = "cart.payment-methods.transform.run"
  input_query = "src/cart_payment_methods_transform_run.graphql"
  export = "cart_payment_methods_transform_run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/my-function-payment-ext.wasm"
  watch = [ "src/**/*.rs" ]

  [extensions.ui.paths]
  create = "/functionpayment"
  details = "/functionpayment"
