type = "web_pixel_extension"
name = "my-web-pixel-ext"

runtime_context = "strict"

[settings]
type = "object"

[settings.fields.ga4]
name = "GA4"
description = "GA4 enabled or not"
type = "single_line_text_field"
validations =  [
  { name = "min", value = "1" }
]


