
uid = "13adb51c-bdad-8dd0-ba2a-054d182b63554b719867"
type = "web_pixel_extension"
name = "my-web-pixel-ext"

runtime_context = "strict"

[customer_privacy]
analytics = true
marketing = true
preferences = false
sale_of_data = "enabled"

[settings]
type = "object"

[settings.fields.ga4Id]
name = "GA4 measurement ID"
description = "The measurement ID for the GA4 data stream"
type = "single_line_text_field"
validations = [
  { name = "min", value = "1" }
]

[settings.fields.ga4Sec]
name = "GA4 API secret"
description = "The Measurement Protocol API secret for the GA4 data stream"
type = "single_line_text_field"
validations = [
  { name = "min", value = "1" }
]

[settings.fields.ga4Debug]
name = "Validate GA4 events"
description = "Send events to the GA4 validation endpoint"
type = "single_line_text_field"
validations = [
  { name = "choices", value = "[\"true\", \"false\"]" }
]
