# Read more on extension settings at https://shopify.dev/api/checkout-extensions/checkout/configuration 
# https://shopify.dev/docs/apps/checkout/custom/banners/getting-started

type = "checkout_ui_extension"
name = "Barebone App UI extension"

extension_points = [
  'Checkout::Dynamic::Render',
  'Checkout::Contact::RenderAfter',
  'Checkout::Actions::RenderBefore'
]

# https://shopify.dev/docs/api/checkout-ui-extensions/apis/standardapi#properties-propertydetail-appmetafields
[[metafields]]
namespace = "barebone_app_upsell"
key = "product_id"

[[metafields]]
namespace = "barebone_app"
key = "url"

[capabilities]
network_access = true
block_progress = true
api_access = true

[settings]
  [[settings.fields]]
  key = "validation_ip"
  type = "single_line_text_field"
  name = "IP address to block chgeckouts"
  description = "Specify an IP address to block checkouts (for black lists, etc.)" 
  [[settings.fields]]
  key = "validation_text"
  type = "single_line_text_field"
  name = "Text to block checkouts"
  description = "Specify an text to block checkouts (for comming soon mode, etc.)"
  [[settings.fields]]
  key = "validation_quantity"
  type = "number_integer"
  name = "Quantity to clear carts"
  description = "Specify a quantity to clear carts zero (for fraud protection, etc.)"

