# Read more on extension settings at https://shopify.dev/api/checkout-extensions/checkout/configuration 
# https://shopify.dev/docs/apps/checkout/custom/banners/getting-started

type = "checkout_ui_extension"
name = "Barebone App UI extension"

extension_points = [
  'Checkout::Dynamic::Render',
  'Checkout::DeliveryAddress::RenderBefore',
  'Checkout::Actions::RenderBefore'
]

# https://shopify.dev/docs/api/checkout-ui-extensions/apis/standardapi#properties-propertydetail-appmetafields
[[metafields]]
namespace = "barebone_app_upsell"
key = "product_id"

[[metafields]]
namespace = "barebone_app"
key = "url"

[capabilities]
network_access = true
block_progress = true
api_access = true

[settings]
  [[settings.fields]]
  key = "upsell_banner_title"
  type = "single_line_text_field"
  name = "Upsell Banner title"
  description = "This is a special offer for you!"

  [[settings.fields]]
  key = "validation_message"
  type = "single_line_text_field"
  name = "Shiiping address validation message"
  description = "You are using wrong characters for the target country address."

