import { index, layout, route } from '@react-router/dev/routes';

export default [
  layout('AppShell.jsx', [
    index('routes/index.jsx'),
    route('auth', 'routes/auth.jsx'),
    route('sessiontoken', 'routes/sessiontoken.jsx'),
    route('adminlink', 'routes/adminlink.jsx'),
    route('themeapp', 'routes/themeapp.jsx'),
    route('functiondiscount', 'routes/functiondiscount.jsx'),
    route('functionshipping', 'routes/functionshipping.jsx'),
    route('functionpayment', 'routes/functionpayment.jsx'),
    route('functioncart', 'routes/functioncart.jsx'),
    route('webpixel', 'routes/webpixel.jsx'),
    route('postpurchase', 'routes/postpurchase.jsx'),
    route('checkoutui', 'routes/checkoutui.jsx'),
    route('customeraccountui', 'routes/customeraccountui.jsx'),
    route('eventsubscription', 'routes/eventsubscription.jsx'),
    route('ordermanage', 'routes/ordermanage.jsx'),
    route('bulkoperation', 'routes/bulkoperation.jsx'),
    route('storefront', 'routes/storefront.jsx'),
    route('posui', 'routes/posui.jsx'),
  ]),
  route('auth/callback', 'routes/auth.callback.jsx'),
  route('callback', 'routes/callback.jsx'),
  route('customer-account/login', 'routes/customer-account.login.jsx'),
  route('customer-account/callback', 'routes/customer-account.callback.jsx'),
  route('customer-account/logout', 'routes/customer-account.logout.jsx'),
  route('customer-account/session', 'routes/customer-account.session.jsx'),
  route('authenticated', 'routes/authenticated.jsx'),
  route('ordermanage.json', 'routes/ordermanage-json.jsx'),
  route('bulkoperation.json', 'routes/bulkoperation-json.jsx'),
  route('storefront.json', 'routes/storefront-json.jsx'),
  route('storefront/plain', 'routes/storefront-plain.jsx'),
  route('mocklogin', 'routes/mocklogin.jsx'),
  route('appproxy', 'routes/appproxy.jsx'),
  route('fulfillment_order_notification', 'routes/fulfillment-order-notification.jsx'),
  route('fetch_tracking_numbers.json', 'routes/fetch-tracking-numbers.jsx'),
  route('fetch_stock.json', 'routes/fetch-stock.jsx'),
  route('webhookcommon', 'routes/webhook-action.jsx'),
  route('webhookgdpr', 'routes/webhookgdpr.jsx'),
  route('flowaction', 'routes/flowaction.jsx'),
];
