name = "my-function-discount-ext"
type = "product_discounts"
api_version = "2023-01"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/my-function-discount-ext.wasm"

[ui.paths]
create = "/"
details = "/"
