name = "my-function-discount-ext"
type = "order_discounts"
api_version = "unstable"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/my-function-discount-ext.wasm"
watch = [ "src/**/*.rs" ]

[ui.paths]
create = "/functiondiscount"
details = "/functiondiscount"

# https://shopify.dev/api/functions/input-query-variables
[input.variables]
namespace = "barebone_app_function_discount"
key = "customer_meta"
