name = "my-function-discount-ext"
uid = "b6fe61fd-7371-1552-2859-6fb19ee291d0098c3a5d"
type = "order_discounts"
api_version = "unstable"

[build]
# For old Rust 
#command = "cargo wasi build --release"
#path = "target/wasm32-wasi/release/my-function-discount-ext.wasm"
command = "cargo build --target=wasm32-wasip1 --release"
path = "target/wasm32-wasip1/release/my-function-discount-ext.wasm"
watch = [ "src/**/*.rs" ]

[ui.paths]
create = "/functiondiscount"
details = "/functiondiscount"

# https://shopify.dev/api/functions/input-query-variables
[input.variables]
namespace = "barebone_app_function_discount"
key = "customer_meta"
