import { useState, useCallback } from 'react';
import { useAppBridge } from '@shopify/app-bridge-react';
import { Redirect } from '@shopify/app-bridge/actions';
import { Page, Card, Layout, Link, Badge, List, Button, TextField, BlockStack } from '@shopify/polaris';

import { _getShopFromQuery, _getAdminFromShop } from "../utils/my_util";

// Theme App Extension sample with App Proxies
// See https://shopify.dev/apps/online-store/theme-app-extensions
// See https://shopify.dev/apps/online-store/app-proxies
function ThemeAppExtension() {
    const app = useAppBridge();
    const redirect = Redirect.create(app);

    const shop = _getShopFromQuery(window);

    const [id, setId] = useState('');
    const idChange = useCallback((newId) => setId(newId), []);

    return (
        <Page title="Theme App Extension usage of Schema, Metafields and App Proxies for server communication">
            <BlockStack gap="500">
                <Card sectioned={true}>
                    <Layout>
                        <Layout.Section>
                            <Link url="https://shopify.dev/apps/online-store/theme-app-extensions/extensions-framework" target="_blank">Dev. doc</Link>
                        </Layout.Section>
                        <Layout.Section>
                            <List type="number">
                                <List.Item>
                                    Input your <Badge>Theme App Extension ID</Badge> available in <Badge>'/.env'</Badge> file generated by your first <Badge>`npm run deploy`</Badge>
                                    <TextField
                                        label=""
                                        value={id}
                                        onChange={idChange}
                                        autoComplete="off"
                                        placeholder="Example: 6469a556-0d95-4eec-ad3b-805265b20df2"
                                    />
                                </List.Item>
                                <List.Item>
                                    <Button variant="primary" onClick={() => {
                                        // See https://shopify.dev/apps/online-store/theme-app-extensions/extensions-framework#simplified-installation-flow-with-deep-linking
                                        const path = `/themes/current/editor?context=apps&activateAppId=${id}/app-embed-block`;
                                        console.log(path);
                                        redirect.dispatch(Redirect.Action.ADMIN_PATH, {
                                            path: path,
                                            newContext: true
                                        });
                                    }}>
                                        Active your extension settings in the theme editor
                                    </Button>

                                </List.Item>
                                <List.Item>Add <Link url={`https://${_getAdminFromShop(shop)}/settings/custom_data`} target="_blank">Metafields</Link> for <Badge status='info'>Products</Badge>
                                    in type of <Badge>Product</Badge> and <Badge>Single line text</Badge> and go to the app block section in the theme editor ('Home page' and 'Default product') to set the metafields above with
                                    <Link url={`https://help.shopify.com/en/manual/online-store/themes/theme-structure/sections-and-blocks`} target="_blank">Dynamic sources</Link>
                                    (don't forget to set Metafields to <Link url={`https://${_getAdminFromShop(shop)}/products`} target="_blank">Products</Link>)
                                </List.Item>
                            </List>
                        </Layout.Section>
                    </Layout>
                </Card>
                <Card sectioned={true}>
                    <Layout>
                        <Layout.Section>
                            <Link url="https://shopify.dev/apps/online-store/app-proxies" target="_blank">Dev. doc</Link>
                        </Layout.Section>
                        <Layout.Section>
                            <List type="number">
                                <List.Item>
                                    Subpath prefix: <Badge>apps</Badge> Subpath: <Badge>bareboneproxy</Badge> Proxy URL: <Badge>https://{window.location.hostname}/appproxy</Badge>
                                </List.Item>
                                <List.Item>
                                    <Link url={`https://${shop}/apps/bareboneproxy?your_param=your_value`} target="_blank">Test your proxy</Link>
                                </List.Item>
                                <List.Item>
                                    Check <Link url={`https://${shop}`} target="_blank">your theme storefront</Link> to see how your set extensions show up switching the pages of home and products.
                                </List.Item>
                            </List>
                        </Layout.Section>
                    </Layout>
                </Card>
            </BlockStack>
        </Page>
    );
}

export default ThemeAppExtension