api_version = "2026-07"

[[extensions]]
name = "my-function-shipping-ext"
handle = "my-function-shipping-ext"
uid = "4269092f-36ee-46e5-85bf-86bea1c8ff51"
type = "function"

  [[extensions.targeting]]
  target = "cart.delivery-options.transform.run"
  input_query = "src/cart_delivery_options_transform_run.graphql"
  export = "cart_delivery_options_transform_run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/my-function-shipping-ext.wasm"
  watch = [ "src/**/*.rs" ]

  [extensions.ui.paths]
  create = "/functionshipping"
  details = "/functionshipping"
