name = "my-function-shipping-ext"
uid = "4269092f-36ee-46e5-85bf-86bea1c8ff51"
type = "delivery_customization"
api_version = "unstable"

[build]
# For old Rust
#command = "cargo wasi build --release"
#path = "target/wasm32-wasi/release/my-function-shipping-ext.wasm"
command = "cargo build --target=wasm32-wasip1 --release"
path = "target/wasm32-wasip1/release/my-function-shipping-ext.wasm"
watch = [ "src/**/*.rs" ]

[ui.paths]
create = "/functionshipping"
details = "/functionshipping"
